#!/usr/bin/env bash

set -euo pipefail

# -----------------------------------------------------------------------------
# Project Paths
# -----------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

MAPPING_FILE="$PROJECT_ROOT/deployment/domain-mapping.conf"
OUTPUT_FILE="$PROJECT_ROOT/src/lib/records/prod.ts"

# -----------------------------------------------------------------------------
# Validate input file
# -----------------------------------------------------------------------------

if [[ ! -f "$MAPPING_FILE" ]]; then
    echo "Domain mapping file not found:"
    echo "$MAPPING_FILE"
    exit 1
fi

# -----------------------------------------------------------------------------
# Create output file
# -----------------------------------------------------------------------------

cat > "$OUTPUT_FILE" <<'EOF'
// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE.
// DO NOT EDIT MANUALLY.
// Generated by deployment/scripts/generate-records.sh
// -----------------------------------------------------------------------------

export const prodHostToTenant: Record<string, string> = {
EOF

# -----------------------------------------------------------------------------
# Generate mappings
# -----------------------------------------------------------------------------

COUNT=0

while read -r domain tenant; do

    # Skip empty lines
    [[ -z "${domain:-}" ]] && continue

    # Skip comments
    [[ "$domain" =~ ^# ]] && continue

    printf "  '%s': '%s',\n" "$domain" "$tenant" >> "$OUTPUT_FILE"

    COUNT=$((COUNT + 1)) 

done < "$MAPPING_FILE"

# -----------------------------------------------------------------------------
# Close object
# -----------------------------------------------------------------------------

echo "};" >> "$OUTPUT_FILE"

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------


echo "Generated $COUNT domain mappings."
echo "Output: $OUTPUT_FILE"
